version: '3'
services:
  frontend:
    restart: always
    build: 
      context: ./frontend
      target: release
    ports:
      - "5002:80" 
    depends_on:
      - middleware

  middleware:
    build: ./middleware
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    healthcheck:
      test: 
        [
          "CMD", 
          "healthcheck.sh", 
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
    depends_on: 
      - database
    ports:
      - "2000:80"