version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      target: release  # Target the release stage of the Dockerfile
    ports:
      - "42069:80"  # Map port 80 of the container to port 42069 of the host
    depends_on:
      - middleware

  middleware:
    build: ./middleware
    ports:
      - "5001:5000"
    depends_on:
      - database

  database:
    container_name: database
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
    depends_on: 
      - database
    ports:
      - "2000:80"  # Visit the management page on localhost:2000